apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: ecommerce
type: Opaque
data:
  admin-password: YWRtaW4xMjM=  # admin123
  db-username: YWRtaW4xMjM=     # admin123 (для Keycloak)
  db-password: a2V5Y2xvYWtfcGFzcw==  # keycloak_pass