apiVersion: batch/v1
kind: Job
metadata:
  name: init-kafka
  namespace: ecommerce
spec:
  template:
    spec:
      containers:
        - name: init-kafka
          image: confluentinc/cp-kafka:7.5.0
#          TODO: Создались топики с 1 партицией
          command:
            - /bin/sh
            - -c
            - |
              echo '⏳ Waiting for Kafka cluster to be fully ready (all 3 brokers)...'
              
              # Ждем минимум 3 брокера, проверяем каждые 10 секунд, таймаут 120 секунд
              cub kafka-ready -b kafka-0.kafka-svc.ecommerce.svc.cluster.local:9092,kafka-1.kafka-svc.ecommerce.svc.cluster.local:9092,kafka-2.kafka-svc.ecommerce.svc.cluster.local:9092 3 120
              
              echo '✅ All 3 Kafka brokers are ready!'
              
              # Дополнительная пауза для стабилизации контроллера
              echo 'Waiting 10 seconds for controller election to stabilize...'
              sleep 10
              
              echo '📋 Creating topics...'
              
              kafka-topics --bootstrap-server kafka-0.kafka-svc.ecommerce.svc.cluster.local:9092 --create --if-not-exists --topic order-created --partitions 12 --replication-factor 3
              echo '✓ order-created created'
              
              kafka-topics --bootstrap-server kafka-0.kafka-svc.ecommerce.svc.cluster.local:9092 --create --if-not-exists --topic order-events-dlq --partitions 12 --replication-factor 3
              echo '✓ order-events-dlq created'
              
              kafka-topics --bootstrap-server kafka-0.kafka-svc.ecommerce.svc.cluster.local:9092 --create --if-not-exists --topic inventory-reserved --partitions 12 --replication-factor 3
              echo '✓ inventory-reserved created'
              
              kafka-topics --bootstrap-server kafka-0.kafka-svc.ecommerce.svc.cluster.local:9092 --create --if-not-exists --topic payment-completed --partitions 12 --replication-factor 3
              echo '✓ payment-completed created'
              
              kafka-topics --bootstrap-server kafka-0.kafka-svc.ecommerce.svc.cluster.local:9092 --create --if-not-exists --topic payment-failed --partitions 12 --replication-factor 3
              echo '✓ payment-failed created'
              
              kafka-topics --bootstrap-server kafka-0.kafka-svc.ecommerce.svc.cluster.local:9092 --create --if-not-exists --topic order-rejected --partitions 12 --replication-factor 3
              echo '✓ order-rejected created'
              
              echo '==============================================='
              echo '✅ All topics created successfully!'
              echo '==============================================='
              
              kafka-topics --bootstrap-server kafka-0.kafka-svc.ecommerce.svc.cluster.local:9092 --list
      restartPolicy: OnFailure
  backoffLimit: 3