apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-postgres-init
  namespace: ecommerce
data:
  init.sql: |
    CREATE DATABASE keycloak_db;
    GRANT ALL PRIVILEGES ON DATABASE keycloak_db TO postgres;