server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgresql:5432/order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-0.kafka:29092,kafka-1.kafka:29092,kafka-2.kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
        max.in.flight.requests.per.connection: 5
        retries: 10
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:order-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    properties:
      spring.json.add.type.headers: true
      spring.json.write.dates.as.timestamps: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/ecommerce-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://keycloak:8080/realms/ecommerce-realm/protocol/openid-connect/certs}

outbox:
  publisher:
    fixed-delay-ms: 3000
    max-attempts: 10
    retry-delay-seconds: 5

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  show-actuator: true

# Eureka отключаем — в K8s используем DNS service discovery
eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.example.order: ${LOG_LEVEL:INFO}
    org.springframework.web: WARN
    org.springframework.kafka: ${KAFKA_LOG_LEVEL:WARN}
    org.springframework.security: WARN