apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-service-postgresql-statefulset
  namespace: ecommerce
spec:
  serviceName: "inventory-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service-postgresql
  template:
    metadata:
      labels:
        app: inventory-service-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: inventory_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: inventory-postgres-data
              mountPath: /var/lib/postgresql

  volumeClaimTemplates:
    - metadata:
        name: inventory-postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-postgresql-service
  namespace: ecommerce
spec:
  selector:
    app: inventory-service-postgresql
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP
